### ISSUE TITLE
Question for the stess-ng

### ISSUE THREAD

**Issue by wangyihanlarry** [ColinIanKing/pagein#1]
Hi buddy,

How are u doing these days? I am investigating the stress-ng and got the following questions, could you please help to check ?

1, how should I know which stressors have the verify mode, are there any command to list those all?

Verify mode
Some stressors have a verification mode. A stress test is run and the results are checked, if the results are incorrect then stress-ng will flag up a warning error message. Suppose we want to run some exhaustive memory checks on a blob of virtually mapped memory via the vm stressor, enable the --verify mode and this will sanity check that the read/write results on the memory:

stress-ng --vm 1 --vm-bytes 2G --verify -v
Note that not all stressors have a verify mode, and enabling it will reduce the bogo op stats as there is an extra verification step being invoked.

2, The same as question 1, can I get the list for the stressors which have more than one method

Methods
Some stressors contain more than one method of causing stress. For example, the cpu stress test contains a wide range of ways to exercise a CPU; these are known as "methods". You can see all the methods using the "which" operator:

stress-ng --cpu-method which

3, some of the stressor could specify the load level, how can I figure out all of them
to support these opeartion?
stress-ng --cpu 0 -l 20

**Comment by ColinIanKing** [comment]
posted to the wrong repo. Please repost in the stress-ng repository
